# Generated by Django 5.0.6 on 2024-06-04 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appyoutube', '0005_video_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='perfil',
        ),
        migrations.AddField(
            model_name='perfil',
            name='videos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appyoutube.video'),
            preserve_default=False,
        ),
    ]
